### PR TITLE
[PATIENTAPP-59] Add FHIR Resource: Allergy/Intolerance

### PR DESCRIPTION
**Pull request by sflejszman**
Issue:  https://1uphealth.atlassian.net/browse/PATIENTAPP-59

---

##### PR Checklist
- [x] Give this PR a meaningful title
- [x] Add a link to the related issue at the top of this description (above)
- [x] Connect this PR with the related issue via ZenHub with the button below this text box (or at the bottom of the page after the PR is created)
- [x] Ensure your branch is up to date with the target branch and resolve any conflicts
- [x] Answer the below questions to describe your PR for reviewers
- [x] Request at least two reviewers using the "Reviewers" section on the right, usually including at least one reviewer from your team
- [x] Notify the requested reviewers in the #code-review Slack channel once the PR is ready for review

---

## Why are these changes needed?

Due to the latest redesign, which introduced bootstrapped version of UI components, creating the AllergyIntolerance component was necessary to fulfill the requirements.

## What changed?

Screenshot 2022-01-03 at 14 51 14

## How are these changes tested?

All automatic tests are passing
The ExplanationOfBenefit component might be tested manually by viewing the current version of the [deployed storybook](https://fhir-react-lib-test-storybook.s3.amazonaws.com/branch/PATIENTAPP-59-Allergy-intolerance/index.html?path=/story/allergyintolerance--default-visualization-dstu-2)

### CODE REVIEW

**Review by beck1uphealth — CHANGES_REQUESTED** [review]
Can we change how the mobile view words wrap? the last letter of "severe" got put on a new line by itself  Screen Shot 2022-01-03 at 11 01 47 AM

**Comment by sflejszman** [comment]
Done and ready for re-check 👍 
Screenshot 2022-01-04 at 10 43 08
Screenshot 2022-01-04 at 10 43 19

**Review by michal-maksajda — APPROVED** [review]
👍

**Review by beck1uphealth — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
